### ISSUE TITLE
'afn' conflict with JavaScript (ES6) code snippets

### ISSUE THREAD

**Issue by gluons** [akamud/vscode-javascript-snippet-pack#2]
`afn` snippet of this extension conflict with [JavaScript (ES6) code snippets](https://marketplace.visualstudio.com/items?itemName=xabikos.JavaScriptSnippets)

xabikos/vscode-javascript#9

**Comment by akamud** [comment]
I'm sorry but I don't see any way we could avoid this :/

Do you have any suggestion?

**Comment by gluons** [comment]
Is it possible that either this extension or [JavaScript (ES6) code snippets](https://marketplace.visualstudio.com/items?itemName=xabikos.JavaScriptSnippets) change prefix `afn`?

Otherwise, I should uninstall one. That's sad.

**Comment by akamud** [comment]
I want to keep this exactly as a port of the VS extension from Mads, so I don't plan on changing any of the shortcuts. Sorry :/

**Comment by gluons** [comment]
@akamud OK. I'll wait for [JavaScript (ES6) code snippets](https://marketplace.visualstudio.com/items?itemName=xabikos.JavaScriptSnippets) author's response.

**Comment by gluons** [comment]
Fix in [JavaScript (ES6) snippets v1.1.0](https://github.com/xabikos/vscode-javascript/releases/tag/1.1.0). 
Many thanks to @xabikos.

**Comment by akamud** [comment]
Awesome!
