### ISSUE TITLE
Optional semicolons

### ISSUE THREAD

**Issue by axdemelas** [akamud/vscode-javascript-snippet-pack#4]
Semicolons are optional. I think that who use it should add instead of who doesn't use have to remove it as an obstacle.

At least provide some interface to omit it, something like:

```js
cl ~~> console.log($1)

cl; ~~> console.log($1);
```

**Comment by akamud** [comment]
Hi @ahlechandre, thanks for the feedback. I plan to keep this a direct port of the Atom/VS extensions, so I won't be making any changes that differs from them.

Remember you can always fork the project and customize it.

**Comment by WinniKlenk** [comment]
'Remember you can always fork the project and customize it.'
Hi akamud, sorry for the maybe silly quesetio but as a bloody beginner I dont know how to manage this for vscode. Do you have any suggestion because I also wont have the semikolo all the time present
